In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/data.csv',na_values = ['#NAME?'])
data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States,<=50K
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,<=50K
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States,<=50K
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States,<=50K

In [ ]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
data.nunique()

age                 69
workclass            8
fnlwgt            4507
education           17
education_num       17
marital_status       7
occupation          15
relationship         6
race                 6
sex                  3
capital_gain        83
capital_loss        55
hours_per_week      74
native_country      40
income               2
dtype: int64

In [ ]:
data['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [ ]:
data['income']=[0 if x=='<=50K' else 1 for x in data['income']]

In [ ]:
data['income'].unique()

array([0, 1])

In [ ]:
x=data.drop(columns=['income'])
#or data.drop('income', axis ='columns')
# ordata.drop('income', axis = 1)
x

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States

In [ ]:
y=data['income']

In [ ]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: income, Length: 5000, dtype: int64

In [ ]:
x.isnull().sum()

age                48
workclass           0
fnlwgt            107
education           0
education_num      57
marital_status      0
occupation          0
relationship        0
race              264
sex                47
capital_gain        0
capital_loss        0
hours_per_week      0
native_country      0
dtype: int64

In [ ]:
len(x['education'].unique())

17

In [ ]:
pd.get_dummies(x['education'])

,10th,11th,12th,1st-4th,5th-6th,7th-8th,9th,?,Assoc-acdm,Assoc-voc,Bachelors,Doctorate,HS-grad,Masters,Preschool,Prof-school,Some-college
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
for col in x.columns:
  if x[col].dtypes == 'object':
    uniq = len(x[col].unique())
    print(f'Feature : {col} has {uniq} categories')

Feature : workclass has 8 categories
Feature : education has 17 categories
Feature : marital_status has 7 categories
Feature : occupation has 15 categories
Feature : relationship has 6 categories
Feature : race has 6 categories
Feature : sex has 3 categories
Feature : native_country has 40 categories

In [ ]:
x['native_country'].value_counts().sort_values(ascending=True)

native_country
Hong                             1
Scotland                         1
Thailand                         2
Yugoslavia                       2
Laos                             2
Honduras                         3
Outlying-US(Guam-USVI-etc)       3
Peru                             3
France                           3
Trinadad&Tobago                  4
Ireland                          4
Cambodia                         4
Ecuador                          4
Nicaragua                        5
Columbia                         5
Haiti                            6
Greece                           6
Portugal                         7
Japan                            9
South                            9
Poland                           9
Taiwan                          10
Vietnam                         10
Guatemala                       10
Iran                            11
India                           12
Italy                           12
Dominican-Republic              13
Cuba                            14
China                           15
Jamaica                         15
El-Salvador                     16
England                         16
Puerto-Rico                     16
Germany                         22
Philippines                     22
Canada                          28
?                               97
Mexico                         104
United-States                 4465
Name: count, dtype: int64

In [ ]:
x['native_country']=['United-States' if x=='United-States' else 'Others' for x in x['native_country']]

In [ ]:
x

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Others
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States